### ISSUE TITLE
engineclient -> part of launcher?

### ISSUE THREAD

**Issue by BlackPhrase** [BlackPhrase/magenta#15]
More control over the application execution order and fewer problems with dedicated server mode

**Comment by Sh1ft0x0EF** [comment]
Also possible to load the module in launcher and connect it with engine module at that stage so this way engine won't know about the engineclient module

**Comment by Sh1ft0x0EF** [comment]
But I need to restore the event system for this... (engineclient should subscribe to the engine events)
