### ISSUE TITLE
Change the license to LGPL

### ISSUE THREAD

**Issue by BlackPhrase** [BlackPhrase/magenta#20]
Game/client logic modules should be able to be closed-source

**Comment by Sh1ft0x0EF** [comment]
I'm probably unable to do that...
But it's possible to restore these lines:

> 	In addition, as a special exception, the author gives permission to
> 	link the code of this program with the Half-Life Game Engine ("HL
> 	Engine") and Modified Game Libraries ("MODs") developed by Valve,
> 	L.L.C ("Valve"). You must obey the GNU General Public License in all
> 	respects for all of the code used other than the HL Engine and MODs
> 	from Valve. If you modify this file, you may extend this exception
> 	to your version of the file, but you are not obligated to do so. If
> 	you do not wish to do so, delete this exception statement from your
> 	version.

But I'm not pretty sure about legal side of this "trick"
Maybe it's also possible to apply the LGPL as a second license(...?)
