### ISSUE TITLE
cvar_t wrapping

### ISSUE THREAD

**Issue by BlackPhrase** [BlackPhrase/magenta#8]
Note to just to remember and to finally fix it

cvar_t struct contains "next" element in order to be able to use it as a singly-linked list
I can wrap it and create an stl list from the wrapper class
but I need to manually bind next element of each wrapped cvar_t instances to next wrapped element inside of stl list...

**Comment by Sh1ft0x0EF** [comment]
There's two possible ways to let the engine know about some cvar:
1) register it (link it);
2) ask the engine to create a new one;

In both cases, it's possible to link the wrapped cvar with the next one so technically it should work
